<<<<<<< HEAD
name: Fixer

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Style code fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '7.4'

      - name: Composer
        run: composer install

      - name: Style code fixer
        run: composer fix-style

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Style code
=======
name: Fixer

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  build:
    permissions:
      contents: write  # for stefanzweifel/git-auto-commit-action to push code in repo
    name: Style code fixer

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACTIONS_TOKEN }}

      - uses: shivammathur/setup-php@v2
        with:
          php-version: '8.0'

      - name: Composer
        run: composer install

      - name: Style code fixer
        run: composer fix-style

      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Style code
>>>>>>> 0e43d46bd70bbf8f4ae92c2780080d51c6ccd837
